name: Mind Bending
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6512118605896831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6280252381693572
  lightness: 0.013697223737835884
  saturation: 0.2801068047992885
  rhythmicContrast: 0.37328493874520063
purpose: []
